{
 "title": "Slurm stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "slurm_partition",
    "label": "slurm_partition",
    "query": "show tag values with key in (\"partition\")"
   },
   {
    "name": "node",
    "query": "show tag values with key in (\"node\")"
   }
  ]
 },
 "panels": [
  {
   "title": "node states overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "nodes" }
   ],
   "targets": [
    {
     "alias": "allocated",
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "slurm.node_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "ALLOCATED" }
     ]
    },
    {
     "alias": "mixed",
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "slurm.node_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "MIXED" }
     ]
    },
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "slurm.node_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "IDLE" }
     ]
    },
    {
     "alias": "resv",
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "slurm.node_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "RESERVED" }
     ]
    }
   ]
  },
  {
   "title": "drained/dranING nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "node cnt" }
   ],
   "targets": [
    {
     "alias": "drained_nodes",
     "groupBy": [
      { "params": [ "/^$node$/" ], "type": "tag" }
     ],
     "measurement": "slurm.node_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "drained" }
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "queue stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "jobs" }
   ],
   "targets": [
    {
     "alias": "amount of running jobs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.queue_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "running" }
     ]
    },
    {
     "alias": "waiting jobs in queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.queue_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "waiting" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "slurm_partition" },
  {
   "title": "$slurm_partition partition usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "node cnt" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "total" }
     ]
    },
    {
     "alias": "allocated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "allocated" }
     ]
    },
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "idle" }
     ]
    },
    {
     "alias": "other",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "other" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "$slurm_partition partition usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "node cnt" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "total" }
     ]
    },
    {
     "alias": "allocated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "allocated" }
     ]
    },
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "idle" }
     ]
    },
    {
     "alias": "other",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "other" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$slurm_partition partition usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "node cnt" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "total" }
     ]
    },
    {
     "alias": "allocated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "allocated" }
     ]
    },
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "idle" }
     ]
    },
    {
     "alias": "other",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "other" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "$slurm_partition partition usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "node cnt" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "total" }
     ]
    },
    {
     "alias": "allocated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "allocated" }
     ]
    },
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "idle" }
     ]
    },
    {
     "alias": "other",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slurm.partition_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "partition", "operator": "=~", "value": "/^$slurm_partition$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "other" }
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } }
 ]
}